---
- name: setup macos
  hosts: localhost
  become: false
  vars_files:
    - vars.yaml
  handlers:
    - name: "Restart Dock"
      shell: "killall Dock"
    - name: "Restart Finder"
      shell: "killall Finder"
  tasks:
    - import_tasks: tasks/homebrew.yaml
    - import_tasks: tasks/macappstore.yaml
    - import_tasks: tasks/defaults.yaml
    - import_tasks: tasks/dotfiles-macos.yaml
