---
- name: Setup Homebrew Taps
  homebrew_tap:
    name: "{{ brew_taps }}"
    state: present

- name: Install Homebrew Cask Packages
  homebrew_cask:
    name: "{{ brew_cask_packages }}"
    state: latest
  when: ansible_distribution == 'MacOSX'

- name: Install Mac App Store CLI
  homebrew:
    name: mas
    state: latest
  when: ansible_distribution == 'MacOSX'

- name: Install Homebrew Packages
  homebrew:
    name: "{{ homebrew_packages }}"
    state: latest
